### ISSUE TITLE
Создать логику игры

### ISSUE THREAD

**Issue by thehighestmath** [thehighestmath/sea_battle#9]

**Comment by Akibardin** [comment]
Смена состояний

**Comment by Akibardin** [comment]
Ход игрока

**Comment by Akibardin** [comment]
Эхолокация - подсказка для игрока, где находится противник. Опционально

**Comment by Akibardin** [comment]
автовыстрелы вокруг убитого корабля

**Comment by thehighestmath** [comment]
- [x] Смена состояний
- [x] Ход игрока 
- [x] Автовыстрелы вокруг убитого корабля
- [ ] Эхолокация - подсказка для игрока, где находится противник. Опционально
